language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements-build.txt
  - pip install https://github.com/ursacomputing/conbench/archive/main.zip
  - pip install coveralls
  - python setup.py install
script:
  - coverage run --source benchmarks -m pytest benchmarks/tests/
after_success:
  - coveralls
