name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      # Note, if ubuntu-latest changes to a different release, we will need to 
      # swap `focal` below to what that new name is for that release.
      RSPM: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
    steps:
      - name: Checkout benchmarks
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Install Python dependencies
        run: |
          python setup.py develop
          pip install -r requirements-test.txt
          pip install -r requirements-build.txt
          pip install https://github.com/ursacomputing/conbench/archive/main.zip
          pip install coveralls
      - name: Lint (black)
        run: |
          black . --check
      - name: Lint (flake8)
        run: |
          flake8
      - name: Arrow for C++ benchmarks
        run: |
          git clone https://github.com/apache/arrow.git
          pip install arrow/dev/archery
          sudo apt-get install libjemalloc-dev libboost-dev libboost-filesystem-dev libboost-system-dev libboost-regex-dev
      - name: Install libcurl (for R arrow)
        run: |
          sudo apt-get -y install libssl-dev libcurl4-openssl-dev
      - name: Install R dependencies
        run: |
          install.packages('remotes')
          install.packages('arrow')
          remotes::install_github('ursacomputing/arrowbench')
        shell: Rscript {0}
        env:
          LIBARROW_BINARY: TRUE
      - name: Run tests
        run: |
          export ARROW_SRC=$(pwd)/arrow/
          echo $ARROW_SRC
          coverage run --source benchmarks -m pytest --run-slow benchmarks/tests/
      - name: Publish coverage
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
